{% set name = "django-maintenance-mode" %}
{% set version = "0.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-maintenance-mode-{{ version }}.tar.gz
  sha256: 57595795062156d5f3f712c885acc18b77a303425bf78b5de80e7fd47d9ab433

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - django >=1.7

about:
  home: https://github.com/fabiocaccamo/django-maintenance-mode
  summary: django-maintenance-mode shows a 503 error page when maintenance-mode is on.
  license: MIT
  # License file manually packaged. See: https://github.com/fabiocaccamo/django-maintenance-mode/pull/69
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - esloch
